# Generated by Django 4.1 on 2022-08-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.FilePathField(verbose_name='/gallery')),
                ('image_caption', models.CharField(max_length=200)),
            ],
        ),
    ]
