# Generated by Django 4.1 on 2022-08-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_tutorial_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Image',
        ),
    ]
