# Generated by Django 4.1 on 2022-08-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
    ]
